"""baseline_2025_12_02_clean

Revision ID: 356fb34b6f4b
Revises: 
Create Date: 2025-12-02 12:03:21.417968

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '356fb34b6f4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bargain_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('business_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=True, comment='Auto-generated: BP-IND-SEL-0001'),
    sa.Column('partner_type', sa.String(length=20), nullable=True, comment='DEPRECATED: seller, buyer, trader, broker, sub_broker, transporter, controller, financer, shipping_agent, importer, exporter'),
    sa.Column('service_provider_type', sa.String(length=50), nullable=True, comment='For service providers: broker, sub_broker, transporter, controller, financer, shipping_agent'),
    sa.Column('trade_classification', sa.String(length=20), nullable=True, comment='DEPRECATED: domestic, exporter (foreign selling to India), importer (foreign buying from India)'),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('trade_name', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('business_entity_type', sa.String(length=100), nullable=True, comment='proprietorship, partnership, llp, private_limited, public_limited, corporation'),
    sa.Column('registration_date', sa.Date(), nullable=True, comment='From tax registration'),
    sa.Column('entity_class', sa.String(length=20), nullable=True, comment='business_entity (can trade) OR service_provider (cannot trade)'),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=True, comment='Auto-detected from verified documents:\n        {\n            "domestic_buy_india": bool,\n            "domestic_sell_india": bool,\n            "domestic_buy_home_country": bool,\n            "domestic_sell_home_country": bool,\n            "import_allowed": bool,\n            "export_allowed": bool,\n            "auto_detected": bool,\n            "detected_from_documents": ["GST", "PAN", "IEC", ...],\n            "detected_at": "ISO timestamp",\n            "manual_override": bool,\n            "override_reason": str | null\n        }\n        CRITICAL: Foreign entities can ONLY trade in home country (domestic_buy_india=false, domestic_sell_india=false)\n        '),
    sa.Column('master_entity_id', sa.UUID(), nullable=True, comment='If this is a branch/subsidiary, points to master entity'),
    sa.Column('is_master_entity', sa.Boolean(), nullable=False, comment='True if this entity has branches/subsidiaries'),
    sa.Column('corporate_group_id', sa.UUID(), nullable=True, comment='Entities in same group cannot trade with each other (insider trading prevention)'),
    sa.Column('entity_hierarchy', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Full entity hierarchy for compliance:\n        {\n            "ultimate_parent": "Company XYZ Ltd",\n            "parent_chain": ["Parent Corp", "Subsidiary A"],\n            "ownership_percentage": 75.5,\n            "group_structure": "vertical" | "horizontal",\n            "last_updated": "ISO timestamp"\n        }\n        '),
    sa.Column('has_tax_registration', sa.Boolean(), nullable=True),
    sa.Column('tax_id_type', sa.String(length=20), nullable=True, comment='GST, EIN, TRN, VAT, etc.'),
    sa.Column('tax_id_number', sa.String(length=50), nullable=True),
    sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='GST: {gstin, legal_name, trade_name, status, state, directors, additional_places, other_state_gstins}'),
    sa.Column('tax_verified', sa.Boolean(), nullable=True),
    sa.Column('tax_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('pan_name', sa.String(length=500), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=True),
    sa.Column('has_no_gst_declaration', sa.Boolean(), nullable=True),
    sa.Column('no_gst_declaration_url', sa.String(length=1000), nullable=True),
    sa.Column('declaration_reason', sa.String(length=200), nullable=True, comment='commission_agent, turnover_below_threshold, exempted_category'),
    sa.Column('bank_account_name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('bank_account_number', sa.String(length=100), nullable=False),
    sa.Column('bank_routing_code', sa.String(length=50), nullable=False, comment='IFSC (India), Routing (USA), SWIFT/IBAN (International)'),
    sa.Column('bank_verified', sa.Boolean(), nullable=True),
    sa.Column('primary_address', sa.Text(), nullable=False),
    sa.Column('primary_city', sa.String(length=100), nullable=False),
    sa.Column('primary_state', sa.String(length=100), nullable=True),
    sa.Column('primary_postal_code', sa.String(length=20), nullable=False),
    sa.Column('primary_country', sa.String(length=100), nullable=False),
    sa.Column('primary_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('primary_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_geocoded', sa.Boolean(), nullable=True),
    sa.Column('location_confidence', sa.Numeric(precision=5, scale=2), nullable=True, comment='Google Maps geocoding confidence 0-100'),
    sa.Column('primary_contact_name', sa.String(length=200), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=200), nullable=False),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('primary_currency', sa.String(length=3), nullable=False),
    sa.Column('commodities', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='["cotton", "cotton_yarn", "textiles"]'),
    sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('credit_utilized', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True, comment='0=advance, 15, 30, 45'),
    sa.Column('monthly_purchase_volume', sa.String(length=100), nullable=True),
    sa.Column('production_capacity', sa.String(length=200), nullable=True),
    sa.Column('can_arrange_transport', sa.Boolean(), nullable=True),
    sa.Column('has_quality_lab', sa.Boolean(), nullable=True),
    sa.Column('service_details', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Transporter: {fleet_size, routes, vehicle_types, has_own_vehicles, transport_license}, Broker: {license_number, exchange, commission_structure}'),
    sa.Column('risk_score', sa.Integer(), nullable=True, comment='0-100'),
    sa.Column('risk_category', sa.String(length=20), nullable=True, comment='low, medium, high, critical'),
    sa.Column('risk_assessment', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Detailed scoring breakdown and flags'),
    sa.Column('last_risk_assessment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True, comment='Initial KYC verification date (approval date)'),
    sa.Column('kyc_expiry_date', sa.Date(), nullable=True, comment='1 year from approval - triggers renewal'),
    sa.Column('kyc_status', sa.String(length=20), nullable=True, comment='pending, verified, expired, renewal_required'),
    sa.Column('last_kyc_renewal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, approved, rejected, suspended, inactive'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('max_employees_allowed', sa.Integer(), nullable=True),
    sa.Column('current_employee_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['master_entity_id'], ['business_partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_code')
    )
    op.create_index(op.f('ix_business_partners_corporate_group_id'), 'business_partners', ['corporate_group_id'], unique=False)
    op.create_index(op.f('ix_business_partners_country'), 'business_partners', ['country'], unique=False)
    op.create_index(op.f('ix_business_partners_entity_class'), 'business_partners', ['entity_class'], unique=False)
    op.create_index(op.f('ix_business_partners_legal_name'), 'business_partners', ['legal_name'], unique=False)
    op.create_index(op.f('ix_business_partners_master_entity_id'), 'business_partners', ['master_entity_id'], unique=False)
    op.create_index(op.f('ix_business_partners_pan_number'), 'business_partners', ['pan_number'], unique=False)
    op.create_index(op.f('ix_business_partners_partner_type'), 'business_partners', ['partner_type'], unique=False)
    op.create_index(op.f('ix_business_partners_tax_id_number'), 'business_partners', ['tax_id_number'], unique=True)
    op.create_table('capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_category'), 'capabilities', ['category'], unique=False)
    op.create_index(op.f('ix_capabilities_code'), 'capabilities', ['code'], unique=True)
    op.create_table('commodities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('base_unit', sa.String(length=50), server_default='KG', nullable=False),
    sa.Column('trade_unit', sa.String(length=50), nullable=True),
    sa.Column('rate_unit', sa.String(length=50), nullable=True),
    sa.Column('standard_weight_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_category'), 'commodities', ['category'], unique=False)
    op.create_index(op.f('ix_commodities_hsn_code'), 'commodities', ['hsn_code'], unique=False)
    op.create_index(op.f('ix_commodities_name'), 'commodities', ['name'], unique=False)
    op.create_table('delivery_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('includes_freight', sa.Boolean(), nullable=False),
    sa.Column('includes_insurance', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', 'PROCESSING', name='outboxstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_aggregate_id'), 'event_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_aggregate_type'), 'event_outbox', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_created_at'), 'event_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_idempotency_key'), 'event_outbox', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_event_outbox_next_retry_at'), 'event_outbox', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_status'), 'event_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_event_outbox_topic_name'), 'event_outbox', ['topic_name'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_aggregate_id'), 'events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_events_aggregate_type'), 'events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('hsn_knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_name', sa.String(length=200), nullable=False),
    sa.Column('commodity_category', sa.String(length=100), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('hsn_description', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_name', 'hsn_code', name='uix_commodity_hsn')
    )
    op.create_index(op.f('ix_hsn_knowledge_base_commodity_category'), 'hsn_knowledge_base', ['commodity_category'], unique=False)
    op.create_index(op.f('ix_hsn_knowledge_base_commodity_name'), 'hsn_knowledge_base', ['commodity_name'], unique=False)
    op.create_index(op.f('ix_hsn_knowledge_base_hsn_code'), 'hsn_knowledge_base', ['hsn_code'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('CIN', sa.String(length=21), nullable=True),
    sa.Column('PAN', sa.String(length=10), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('pincode', sa.String(length=16), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('threshold_limit', sa.Integer(), nullable=True),
    sa.Column('einvoice_required', sa.Boolean(), nullable=False),
    sa.Column('auto_block_if_einvoice_required', sa.Boolean(), nullable=False),
    sa.Column('fx_enabled', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('theme_color', sa.String(length=64), nullable=True),
    sa.Column('invoice_footer', sa.String(length=1024), nullable=True),
    sa.Column('digital_signature_url', sa.String(length=255), nullable=True),
    sa.Column('tds_rate', sa.Integer(), nullable=True),
    sa.Column('tcs_rate', sa.Integer(), nullable=True),
    sa.Column('audit_firm_name', sa.String(length=255), nullable=True),
    sa.Column('audit_firm_email', sa.String(length=255), nullable=True),
    sa.Column('audit_firm_phone', sa.String(length=32), nullable=True),
    sa.Column('gst_audit_required', sa.Boolean(), nullable=False),
    sa.Column('auto_invoice', sa.Boolean(), nullable=False),
    sa.Column('auto_contract_number', sa.Boolean(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('passing_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_quality_test', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('payment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='IANA timezone (e.g., Asia/Kolkata, America/New_York) for EOD cutoff calculations'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.create_index('ix_settings_locations_city', 'settings_locations', ['city'], unique=False)
    op.create_index('ix_settings_locations_google_place_id', 'settings_locations', ['google_place_id'], unique=False)
    op.create_index('ix_settings_locations_is_active', 'settings_locations', ['is_active'], unique=False)
    op.create_index('ix_settings_locations_pincode', 'settings_locations', ['pincode'], unique=False)
    op.create_index('ix_settings_locations_region', 'settings_locations', ['region'], unique=False)
    op.create_index('ix_settings_locations_state', 'settings_locations', ['state'], unique=False)
    op.create_table('system_commodity_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_category', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_category', 'parameter_name', name='uix_category_parameter')
    )
    op.create_index(op.f('ix_system_commodity_parameters_commodity_category'), 'system_commodity_parameters', ['commodity_category'], unique=False)
    op.create_table('trade_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weightment_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_deduction_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commission_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=True),
    sa.Column('trade_type_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('applies_to', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['trade_type_id'], ['trade_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodity_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodity_varieties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_financial_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_year_split', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_gst',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('branch_code', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('partner_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('amendment_type', sa.String(length=50), nullable=False, comment='add_location, change_bank, update_gst, increase_credit_limit, add_employee'),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('supporting_documents', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Document IDs'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, approved, rejected'),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chat_transcript', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False, comment='gst_certificate, pan_card, bank_proof, transport_license, vehicle_rc, etc.'),
    sa.Column('document_subtype', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_extracted_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_kyc_renewals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('renewal_type', sa.String(length=20), nullable=True, comment='annual, adhoc'),
    sa.Column('renewal_due_date', sa.Date(), nullable=False),
    sa.Column('renewal_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_verified', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='List of document IDs verified'),
    sa.Column('tax_re_verified', sa.Boolean(), nullable=True),
    sa.Column('bank_re_verified', sa.Boolean(), nullable=True),
    sa.Column('risk_re_assessed', sa.Boolean(), nullable=True),
    sa.Column('new_risk_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, in_progress, completed, expired'),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False, comment='principal, additional_same_state, branch_different_state, warehouse, factory, ship_to, bill_to'),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('is_from_gst', sa.Boolean(), nullable=True, comment='Auto-fetched from GST API'),
    sa.Column('gstin_for_location', sa.String(length=15), nullable=True, comment='Different GSTIN if different state'),
    sa.Column('requires_gst', sa.Boolean(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geocoded', sa.Boolean(), nullable=True),
    sa.Column('geocode_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False, comment='truck, trailer, container, etc.'),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('maker_model', sa.String(length=200), nullable=True),
    sa.Column('capacity_tons', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('rc_document_url', sa.String(length=1000), nullable=True),
    sa.Column('insurance_valid_till', sa.Date(), nullable=True),
    sa.Column('fitness_valid_till', sa.Date(), nullable=True),
    sa.Column('permit_type', sa.String(length=100), nullable=True),
    sa.Column('verified_via_rto', sa.Boolean(), nullable=True),
    sa.Column('rto_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data from Parivahan/Vahan API'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_vehicles_vehicle_number'), 'partner_vehicles', ['vehicle_number'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='SUPER_ADMIN, INTERNAL, or EXTERNAL'),
    sa.Column('business_partner_id', sa.UUID(), nullable=True, comment='For EXTERNAL users only'),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='For INTERNAL users only'),
    sa.Column('parent_user_id', sa.UUID(), nullable=True, comment='Parent user ID for sub-users (max 2 per parent)'),
    sa.Column('allowed_modules', postgresql.ARRAY(sa.String()), nullable=True, comment='RBAC: List of modules user can access'),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=False, comment='Whether 2FA with PIN is enabled for this user'),
    sa.Column('pin_hash', sa.String(length=255), nullable=True, comment='Hashed 4-6 digit PIN for 2FA verification'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True, comment='Mobile number for OTP authentication'),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Null for OTP-only users'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Mobile/email verified via OTP'),
    sa.Column('role', sa.String(length=50), nullable=True, comment='User role: partner_user, manager, director, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n\t\t\t(user_type = 'SUPER_ADMIN' AND business_partner_id IS NULL AND organization_id IS NULL) OR\n\t\t\t(user_type = 'INTERNAL' AND business_partner_id IS NULL AND organization_id IS NOT NULL) OR\n\t\t\t(user_type = 'EXTERNAL' AND business_partner_id IS NOT NULL AND organization_id IS NULL)\n\t\t\t", name='ck_user_type_isolation'),
    sa.CheckConstraint("email <> ''", name='ck_user_email_nonempty'),
    sa.CheckConstraint('email IS NOT NULL OR mobile_number IS NOT NULL', name='ck_user_has_email_or_mobile'),
    sa.ForeignKeyConstraint(['business_partner_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True, comment='Registered location ID (NULL for ad-hoc Google Maps locations)'),
    sa.Column('seller_partner_id', sa.UUID(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False, comment='Unit of quantity: BALE, BAG, KG, MT, CANDY, QTL, etc.'),
    sa.Column('quantity_in_base_unit', sa.Numeric(precision=18, scale=6), nullable=True, comment='Auto-calculated quantity in commodity base_unit (KG/METER/LITER)'),
    sa.Column('available_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('sold_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('min_order_quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('allow_partial_order', sa.Boolean(), nullable=False),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_unit', sa.String(length=20), nullable=True, comment='Unit for pricing: per KG, per CANDY, per MT, per BALE'),
    sa.Column('price_per_base_unit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Auto-calculated price per base_unit for consistent matching'),
    sa.Column('price_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_report_url', sa.String(length=500), nullable=True, comment='PDF/Image URL of lab test report'),
    sa.Column('test_report_verified', sa.Boolean(), nullable=False),
    sa.Column('test_report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-extracted parameters from test report: {"length": 29.0, "source": "OCR"}'),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Photo/video URLs for AI quality detection: {"photos": [url1, url2], "videos": [url3]}'),
    sa.Column('ai_detected_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-detected quality from photos/videos: {"color": "white", "trash": 2.5, "confidence": 0.85}'),
    sa.Column('manual_override_params', sa.Boolean(), nullable=False, comment='True if seller manually overrode AI-detected parameters'),
    sa.Column('ai_score_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_suggested_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_price_anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('expected_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_trade_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_precheck_status', sa.String(length=20), nullable=True),
    sa.Column('risk_precheck_score', sa.Integer(), nullable=True),
    sa.Column('seller_exposure_after_trade', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('seller_branch_id', sa.UUID(), nullable=True, comment='Seller branch/location ID (from partner_locations table) for internal trade blocking logic'),
    sa.Column('blocked_for_branches', sa.Boolean(), nullable=False),
    sa.Column('seller_rating_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('seller_delivery_score', sa.Integer(), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_visibility', sa.String(length=20), nullable=False),
    sa.Column('restricted_buyers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_terms', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('delivery_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('delivery_region', sa.String(length=50), nullable=True),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eod_cutoff', sa.DateTime(timezone=True), nullable=True, comment='End-of-day cutoff time (timezone-aware). Availability expires at this time.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_reference', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("risk_precheck_status IS NULL OR risk_precheck_status IN ('PASS', 'WARN', 'FAIL')", name='check_risk_precheck_status_valid'),
    sa.CheckConstraint('available_quantity >= 0', name='check_available_quantity_non_negative'),
    sa.CheckConstraint('available_until IS NULL OR available_from IS NULL OR available_until > available_from', name='check_date_range_valid'),
    sa.CheckConstraint('base_price IS NULL OR base_price > 0', name='check_base_price_positive'),
    sa.CheckConstraint('expected_price IS NULL OR expected_price > 0', name='check_expected_price_positive'),
    sa.CheckConstraint('min_order_quantity IS NULL OR min_order_quantity > 0', name='check_min_order_quantity_positive'),
    sa.CheckConstraint('reserved_quantity >= 0', name='check_reserved_quantity_non_negative'),
    sa.CheckConstraint('risk_precheck_score IS NULL OR (risk_precheck_score >= 0 AND risk_precheck_score <= 100)', name='check_risk_precheck_score_range'),
    sa.CheckConstraint('seller_delivery_score IS NULL OR (seller_delivery_score >= 0 AND seller_delivery_score <= 100)', name='check_seller_delivery_score_range'),
    sa.CheckConstraint('seller_rating_score IS NULL OR (seller_rating_score >= 0 AND seller_rating_score <= 5)', name='check_seller_rating_score_range'),
    sa.CheckConstraint('sold_quantity >= 0', name='check_sold_quantity_non_negative'),
    sa.CheckConstraint('total_quantity > 0', name='check_total_quantity_positive'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['settings_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_branch_id'], ['partner_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_partner_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilities_blocked_for_branches'), 'availabilities', ['blocked_for_branches'], unique=False)
    op.create_index(op.f('ix_availabilities_commodity_id'), 'availabilities', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_availabilities_delivery_region'), 'availabilities', ['delivery_region'], unique=False)
    op.create_index(op.f('ix_availabilities_location_id'), 'availabilities', ['location_id'], unique=False)
    op.create_index(op.f('ix_availabilities_market_visibility'), 'availabilities', ['market_visibility'], unique=False)
    op.create_index(op.f('ix_availabilities_risk_precheck_status'), 'availabilities', ['risk_precheck_status'], unique=False)
    op.create_index(op.f('ix_availabilities_seller_branch_id'), 'availabilities', ['seller_branch_id'], unique=False)
    op.create_index(op.f('ix_availabilities_seller_partner_id'), 'availabilities', ['seller_partner_id'], unique=False)
    op.create_index(op.f('ix_availabilities_status'), 'availabilities', ['status'], unique=False)
    op.create_table('organization_document_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=True),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('reset_annually', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['organization_financial_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_type', 'financial_year_id', name='uq_org_doc_series')
    )
    op.create_table('partner_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('employee_email', sa.String(length=200), nullable=False),
    sa.Column('employee_phone', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True, comment='admin (partner owner), employee'),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='{"create_orders": true, "view_reports": true, "approve_contracts": false}'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_onboarding_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='Auto-defaults to main company - used to track which company processed onboarding'),
    sa.Column('partner_type', sa.String(length=20), nullable=False),
    sa.Column('service_provider_type', sa.String(length=50), nullable=True),
    sa.Column('trade_classification', sa.String(length=20), nullable=True),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('trade_name', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('business_entity_type', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('has_tax_registration', sa.Boolean(), nullable=True),
    sa.Column('tax_id_type', sa.String(length=20), nullable=True),
    sa.Column('tax_id_number', sa.String(length=50), nullable=True),
    sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_verified', sa.Boolean(), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('pan_name', sa.String(length=500), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=True),
    sa.Column('has_no_gst_declaration', sa.Boolean(), nullable=True),
    sa.Column('no_gst_declaration_url', sa.String(length=1000), nullable=True),
    sa.Column('declaration_reason', sa.String(length=200), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('bank_account_number', sa.String(length=100), nullable=False),
    sa.Column('bank_routing_code', sa.String(length=50), nullable=False),
    sa.Column('primary_address', sa.Text(), nullable=False),
    sa.Column('primary_city', sa.String(length=100), nullable=False),
    sa.Column('primary_state', sa.String(length=100), nullable=True),
    sa.Column('primary_postal_code', sa.String(length=20), nullable=False),
    sa.Column('primary_country', sa.String(length=100), nullable=False),
    sa.Column('primary_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('primary_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=200), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=200), nullable=False),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('primary_currency', sa.String(length=3), nullable=False),
    sa.Column('commodities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('service_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_stage', sa.String(length=50), nullable=True, comment='documents, verification, approval'),
    sa.Column('chat_transcript', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=True),
    sa.Column('risk_assessment', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('converted_to_partner_id', sa.UUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_onboarding_applications_organization_id'), 'partner_onboarding_applications', ['organization_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique requirement identifier'),
    sa.Column('requirement_number', sa.String(length=50), nullable=False, comment='Human-readable requirement number: REQ-2025-000001'),
    sa.Column('buyer_partner_id', sa.UUID(), nullable=False, comment='Buyer posting the requirement'),
    sa.Column('commodity_id', sa.UUID(), nullable=False, comment='Required commodity'),
    sa.Column('variety_id', sa.UUID(), nullable=True, comment='Specific variety (optional)'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False, comment='User who created requirement'),
    sa.Column('min_quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='Minimum acceptable quantity'),
    sa.Column('max_quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='Maximum desired quantity'),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False, comment='Unit: bales, kg, MT, grams, etc.'),
    sa.Column('preferred_quantity', sa.Numeric(precision=15, scale=3), nullable=True, comment='Ideal/target quantity'),
    sa.Column('quality_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Quality params with min/max/preferred/exact/accepted/required'),
    sa.Column('max_budget_per_unit', sa.Numeric(precision=15, scale=2), nullable=False, comment='Maximum price buyer willing to pay per unit'),
    sa.Column('preferred_price_per_unit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Target/desired price per unit'),
    sa.Column('total_budget', sa.Numeric(precision=18, scale=2), nullable=True, comment='Overall budget limit for entire purchase'),
    sa.Column('currency_code', sa.String(length=3), server_default='INR', nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('estimated_trade_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='Auto-calculated estimated trade value (preferred_quantity * max_budget_per_unit)'),
    sa.Column('buyer_credit_limit_remaining', sa.Numeric(precision=18, scale=2), nullable=True, comment='Remaining credit limit for this buyer from credit module'),
    sa.Column('buyer_exposure_after_trade', sa.Numeric(precision=18, scale=2), nullable=True, comment='Projected buyer exposure if this trade executes'),
    sa.Column('risk_precheck_status', sa.String(length=20), nullable=True, comment='PASS, WARN, FAIL - Risk assessment status'),
    sa.Column('risk_precheck_score', sa.Integer(), nullable=True, comment='Numeric risk score (0-100, higher is better)'),
    sa.Column('buyer_branch_id', sa.UUID(), nullable=True, comment='Buyer branch/location ID (from partner_locations table) for internal trade blocking logic'),
    sa.Column('blocked_internal_trades', sa.Boolean(), server_default='true', nullable=False, comment='If true, blocks matching with same branch sellers'),
    sa.Column('buyer_rating_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='Buyer rating score (0.00-5.00) from rating module'),
    sa.Column('buyer_payment_performance_score', sa.Integer(), nullable=True, comment='Payment performance score (0-100) based on history'),
    sa.Column('preferred_payment_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of acceptable payment term IDs'),
    sa.Column('preferred_delivery_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of acceptable delivery term IDs'),
    sa.Column('delivery_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Multiple acceptable delivery locations with proximity'),
    sa.Column('delivery_window_start', sa.DateTime(timezone=True), nullable=True, comment='Earliest acceptable delivery date'),
    sa.Column('delivery_window_end', sa.DateTime(timezone=True), nullable=True, comment='Latest acceptable delivery date'),
    sa.Column('delivery_flexibility_hours', sa.Integer(), server_default='168', nullable=False, comment='Flexibility window in hours (default: 7 days = 168 hours)'),
    sa.Column('market_visibility', sa.String(length=20), server_default='PUBLIC', nullable=False, comment='PUBLIC, PRIVATE, RESTRICTED, INTERNAL'),
    sa.Column('invited_seller_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of seller partner IDs for RESTRICTED visibility'),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False, comment='DRAFT, ACTIVE, PARTIALLY_FULFILLED, FULFILLED, EXPIRED, CANCELLED'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False, comment='Requirement valid from date'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False, comment='Requirement valid until date'),
    sa.Column('eod_cutoff', sa.DateTime(timezone=True), nullable=True, comment='End-of-day cutoff time (timezone-aware). Requirement expires at this time.'),
    sa.Column('urgency_level', sa.String(length=20), server_default='NORMAL', nullable=False, comment='URGENT, NORMAL, PLANNING'),
    sa.Column('intent_type', sa.String(length=30), server_default='DIRECT_BUY', nullable=False, comment='DIRECT_BUY, NEGOTIATION, AUCTION_REQUEST, PRICE_DISCOVERY_ONLY'),
    sa.Column('total_matched_quantity', sa.Numeric(precision=15, scale=3), server_default='0', nullable=False, comment='Total quantity matched with availabilities'),
    sa.Column('total_purchased_quantity', sa.Numeric(precision=15, scale=3), server_default='0', nullable=False, comment='Total quantity actually purchased'),
    sa.Column('total_spent', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False, comment='Total amount spent on purchases'),
    sa.Column('active_negotiation_count', sa.Integer(), server_default='0', nullable=False, comment='Number of active negotiations'),
    sa.Column('market_context_embedding', postgresql.ARRAY(sa.Float()), nullable=True, comment='1536-dim vector for semantic matching (OpenAI ada-002 compatible)'),
    sa.Column('ai_suggested_max_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='AI-suggested fair market price'),
    sa.Column('ai_confidence_score', sa.Integer(), nullable=True, comment='AI confidence in price suggestion (0-100)'),
    sa.Column('ai_score_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ML embeddings for smart matching'),
    sa.Column('ai_price_alert_flag', sa.Boolean(), server_default='false', nullable=False, comment='True if AI detects unrealistic budget'),
    sa.Column('ai_alert_reason', sa.Text(), nullable=True, comment='Reason for AI price alert'),
    sa.Column('ai_recommended_sellers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI pre-scored seller suggestions'),
    sa.Column('commodity_equivalents', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Acceptable commodity substitutions with conversion ratios'),
    sa.Column('negotiation_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Self-negotiation settings and thresholds'),
    sa.Column('buyer_priority_score', sa.Float(), server_default='1.0', nullable=False, comment='Buyer priority/trust score (0.5=new, 1.0=standard, 1.5=repeat, 2.0=premium)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Buyer internal notes'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Specifications, drawings, sample images'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When requirement was made ACTIVE'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_branch_id'], ['partner_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_partner_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variety_id'], ['commodity_varieties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_number')
    )
    op.create_index(op.f('ix_requirements_buyer_branch_id'), 'requirements', ['buyer_branch_id'], unique=False)
    op.create_index(op.f('ix_requirements_buyer_partner_id'), 'requirements', ['buyer_partner_id'], unique=False)
    op.create_index(op.f('ix_requirements_commodity_id'), 'requirements', ['commodity_id'], unique=False)
    op.create_table('role_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'capability_id', name='uq_role_capability')
    )
    op.create_index(op.f('ix_role_capabilities_capability_id'), 'role_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_role_capabilities_role_id'), 'role_capabilities', ['role_id'], unique=False)
    op.create_table('user_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'capability_id', name='uq_user_capability')
    )
    op.create_index(op.f('ix_user_capabilities_capability_id'), 'user_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_user_capabilities_expires_at'), 'user_capabilities', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_capabilities_user_id'), 'user_capabilities', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_capabilities_user_id'), table_name='user_capabilities')
    op.drop_index(op.f('ix_user_capabilities_expires_at'), table_name='user_capabilities')
    op.drop_index(op.f('ix_user_capabilities_capability_id'), table_name='user_capabilities')
    op.drop_table('user_capabilities')
    op.drop_index(op.f('ix_role_capabilities_role_id'), table_name='role_capabilities')
    op.drop_index(op.f('ix_role_capabilities_capability_id'), table_name='role_capabilities')
    op.drop_table('role_capabilities')
    op.drop_index(op.f('ix_requirements_commodity_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_buyer_partner_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_buyer_branch_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_partner_onboarding_applications_organization_id'), table_name='partner_onboarding_applications')
    op.drop_table('partner_onboarding_applications')
    op.drop_table('partner_employees')
    op.drop_table('organization_document_series')
    op.drop_index(op.f('ix_availabilities_status'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_seller_partner_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_seller_branch_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_risk_precheck_status'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_market_visibility'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_location_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_delivery_region'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_commodity_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_blocked_for_branches'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_partner_vehicles_vehicle_number'), table_name='partner_vehicles')
    op.drop_table('partner_vehicles')
    op.drop_table('partner_locations')
    op.drop_table('partner_kyc_renewals')
    op.drop_table('partner_documents')
    op.drop_table('partner_amendments')
    op.drop_table('organization_gst')
    op.drop_table('organization_financial_years')
    op.drop_table('organization_bank_accounts')
    op.drop_table('commodity_varieties')
    op.drop_table('commodity_parameters')
    op.drop_table('commission_structures')
    op.drop_table('weightment_terms')
    op.drop_table('trade_types')
    op.drop_index(op.f('ix_system_commodity_parameters_commodity_category'), table_name='system_commodity_parameters')
    op.drop_table('system_commodity_parameters')
    op.drop_index('ix_settings_locations_state', table_name='settings_locations')
    op.drop_index('ix_settings_locations_region', table_name='settings_locations')
    op.drop_index('ix_settings_locations_pincode', table_name='settings_locations')
    op.drop_index('ix_settings_locations_is_active', table_name='settings_locations')
    op.drop_index('ix_settings_locations_google_place_id', table_name='settings_locations')
    op.drop_index('ix_settings_locations_city', table_name='settings_locations')
    op.drop_table('settings_locations')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('payment_terms')
    op.drop_table('passing_terms')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_hsn_knowledge_base_hsn_code'), table_name='hsn_knowledge_base')
    op.drop_index(op.f('ix_hsn_knowledge_base_commodity_name'), table_name='hsn_knowledge_base')
    op.drop_index(op.f('ix_hsn_knowledge_base_commodity_category'), table_name='hsn_knowledge_base')
    op.drop_table('hsn_knowledge_base')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_type'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_event_outbox_topic_name'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_status'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_next_retry_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_idempotency_key'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_created_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_aggregate_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_aggregate_id'), table_name='event_outbox')
    op.drop_table('event_outbox')
    op.drop_table('delivery_terms')
    op.drop_index(op.f('ix_commodities_name'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_hsn_code'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_category'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_capabilities_code'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_category'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_business_partners_tax_id_number'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_partner_type'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_pan_number'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_master_entity_id'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_legal_name'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_entity_class'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_country'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_corporate_group_id'), table_name='business_partners')
    op.drop_table('business_partners')
    op.drop_table('bargain_types')
    # ### end Alembic commands ###
