"""create_settings_locations_table

Revision ID: 025fe632dacf
Revises: 18d3e2c1ff1d
Create Date: 2025-11-21 12:25:20.855454

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '025fe632dacf'
down_revision = '18d3e2c1ff1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settings_locations_city', 'settings_locations', ['city'], unique=False)
    op.create_index('ix_settings_locations_google_place_id', 'settings_locations', ['google_place_id'], unique=False)
    op.create_index('ix_settings_locations_is_active', 'settings_locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_settings_locations_name'), 'settings_locations', ['name'], unique=False)
    op.create_index('ix_settings_locations_pincode', 'settings_locations', ['pincode'], unique=False)
    op.create_index('ix_settings_locations_region', 'settings_locations', ['region'], unique=False)
    op.create_index(op.f('ix_settings_locations_state'), 'settings_locations', ['state'], unique=False)
    op.drop_table('locations')
    op.alter_column('bargain_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bargain_types', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bargain_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bargain_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_bargain_types_is_active', table_name='bargain_types')
    op.create_unique_constraint(None, 'bargain_types', ['name'])
    op.alter_column('commission_structures', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('commission_structures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_commission_commodity_id', table_name='commission_structures')
    op.drop_index('ix_commission_is_active', table_name='commission_structures')
    op.drop_index('ix_commission_trade_type_id', table_name='commission_structures')
    op.drop_constraint('commission_structures_trade_type_id_fkey', 'commission_structures', type_='foreignkey')
    op.drop_constraint('commission_structures_commodity_id_fkey', 'commission_structures', type_='foreignkey')
    op.create_foreign_key(None, 'commission_structures', 'commodities', ['commodity_id'], ['id'])
    op.create_foreign_key(None, 'commission_structures', 'trade_types', ['trade_type_id'], ['id'])
    op.alter_column('commodities', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('commodities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_commodities_is_active', table_name='commodities')
    op.alter_column('commodity_parameters', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('commodity_parameters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_commodity_parameters_commodity_id', table_name='commodity_parameters')
    op.alter_column('commodity_varieties', 'is_standard',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('commodity_varieties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('commodity_varieties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_commodity_varieties_code', table_name='commodity_varieties')
    op.drop_index('ix_commodity_varieties_commodity_id', table_name='commodity_varieties')
    op.alter_column('delivery_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('delivery_terms', 'includes_freight',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('delivery_terms', 'includes_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('delivery_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('delivery_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_delivery_terms_is_active', table_name='delivery_terms')
    op.create_unique_constraint(None, 'delivery_terms', ['name'])
    op.add_column('events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_events_aggregate_composite', table_name='events')
    op.drop_column('events', 'metadata')
    op.alter_column('organization_bank_accounts', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_organization_bank_accounts_is_default', table_name='organization_bank_accounts')
    op.drop_index('ix_organization_bank_accounts_organization_id', table_name='organization_bank_accounts')
    op.alter_column('organization_document_series', 'current_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_document_series', 'reset_annually',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_document_series', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_document_series', 'extra_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_organization_document_series_document_type', table_name='organization_document_series')
    op.drop_index('ix_organization_document_series_financial_year_id', table_name='organization_document_series')
    op.drop_index('ix_organization_document_series_organization_id', table_name='organization_document_series')
    op.alter_column('organization_financial_years', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_financial_years', 'allow_year_split',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_financial_years', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_organization_financial_years_end_date', table_name='organization_financial_years')
    op.drop_index('ix_organization_financial_years_is_active', table_name='organization_financial_years')
    op.drop_index('ix_organization_financial_years_organization_id', table_name='organization_financial_years')
    op.drop_index('ix_organization_financial_years_start_date', table_name='organization_financial_years')
    op.alter_column('organization_gst', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organization_gst', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_organization_gst_gstin', table_name='organization_gst')
    op.drop_index('ix_organization_gst_is_primary', table_name='organization_gst')
    op.drop_index('ix_organization_gst_organization_id', table_name='organization_gst')
    op.alter_column('organizations', 'base_currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'einvoice_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'auto_block_if_einvoice_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'fx_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'gst_audit_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'auto_invoice',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'auto_contract_number',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'extra_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('passing_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('passing_terms', 'requires_quality_test',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('passing_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('passing_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_passing_terms_is_active', table_name='passing_terms')
    op.create_unique_constraint(None, 'passing_terms', ['name'])
    op.alter_column('payment_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payment_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_payment_terms_is_active', table_name='payment_terms')
    op.create_unique_constraint(None, 'payment_terms', ['name'])
    op.drop_index('ix_system_parameters_category', table_name='system_commodity_parameters')
    op.create_index(op.f('ix_system_commodity_parameters_commodity_category'), 'system_commodity_parameters', ['commodity_category'], unique=False)
    op.alter_column('trade_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('trade_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trade_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_trade_types_is_active', table_name='trade_types')
    op.create_unique_constraint(None, 'trade_types', ['name'])
    op.alter_column('weightment_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('weightment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('weightment_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_weightment_terms_is_active', table_name='weightment_terms')
    op.create_unique_constraint(None, 'weightment_terms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weightment_terms', type_='unique')
    op.create_index('ix_weightment_terms_is_active', 'weightment_terms', ['is_active'], unique=False)
    op.alter_column('weightment_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('weightment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('weightment_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'trade_types', type_='unique')
    op.create_index('ix_trade_types_is_active', 'trade_types', ['is_active'], unique=False)
    op.alter_column('trade_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('trade_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('trade_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_system_commodity_parameters_commodity_category'), table_name='system_commodity_parameters')
    op.create_index('ix_system_parameters_category', 'system_commodity_parameters', ['commodity_category'], unique=False)
    op.drop_constraint(None, 'payment_terms', type_='unique')
    op.create_index('ix_payment_terms_is_active', 'payment_terms', ['is_active'], unique=False)
    op.alter_column('payment_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('payment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('payment_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'passing_terms', type_='unique')
    op.create_index('ix_passing_terms_is_active', 'passing_terms', ['is_active'], unique=False)
    op.alter_column('passing_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('passing_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('passing_terms', 'requires_quality_test',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('passing_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'extra_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('organizations', 'auto_contract_number',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'auto_invoice',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'gst_audit_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'fx_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'auto_block_if_einvoice_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'einvoice_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organizations', 'base_currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.create_index('ix_organization_gst_organization_id', 'organization_gst', ['organization_id'], unique=False)
    op.create_index('ix_organization_gst_is_primary', 'organization_gst', ['is_primary'], unique=False)
    op.create_index('ix_organization_gst_gstin', 'organization_gst', ['gstin'], unique=False)
    op.alter_column('organization_gst', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('organization_gst', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_organization_financial_years_start_date', 'organization_financial_years', ['start_date'], unique=False)
    op.create_index('ix_organization_financial_years_organization_id', 'organization_financial_years', ['organization_id'], unique=False)
    op.create_index('ix_organization_financial_years_is_active', 'organization_financial_years', ['is_active'], unique=False)
    op.create_index('ix_organization_financial_years_end_date', 'organization_financial_years', ['end_date'], unique=False)
    op.alter_column('organization_financial_years', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('organization_financial_years', 'allow_year_split',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('organization_financial_years', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_organization_document_series_organization_id', 'organization_document_series', ['organization_id'], unique=False)
    op.create_index('ix_organization_document_series_financial_year_id', 'organization_document_series', ['financial_year_id'], unique=False)
    op.create_index('ix_organization_document_series_document_type', 'organization_document_series', ['document_type'], unique=False)
    op.alter_column('organization_document_series', 'extra_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('organization_document_series', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('organization_document_series', 'reset_annually',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('organization_document_series', 'current_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index('ix_organization_bank_accounts_organization_id', 'organization_bank_accounts', ['organization_id'], unique=False)
    op.create_index('ix_organization_bank_accounts_is_default', 'organization_bank_accounts', ['is_default'], unique=False)
    op.alter_column('organization_bank_accounts', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_events_aggregate_composite', 'events', ['aggregate_id', 'aggregate_type', 'timestamp'], unique=False)
    op.drop_column('events', 'event_metadata')
    op.drop_constraint(None, 'delivery_terms', type_='unique')
    op.create_index('ix_delivery_terms_is_active', 'delivery_terms', ['is_active'], unique=False)
    op.alter_column('delivery_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('delivery_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('delivery_terms', 'includes_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('delivery_terms', 'includes_freight',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('delivery_terms', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index('ix_commodity_varieties_commodity_id', 'commodity_varieties', ['commodity_id'], unique=False)
    op.create_index('ix_commodity_varieties_code', 'commodity_varieties', ['code'], unique=False)
    op.alter_column('commodity_varieties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('commodity_varieties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('commodity_varieties', 'is_standard',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_commodity_parameters_commodity_id', 'commodity_parameters', ['commodity_id'], unique=False)
    op.alter_column('commodity_parameters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('commodity_parameters', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_commodities_is_active', 'commodities', ['is_active'], unique=False)
    op.alter_column('commodities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('commodities', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'commission_structures', type_='foreignkey')
    op.drop_constraint(None, 'commission_structures', type_='foreignkey')
    op.create_foreign_key('commission_structures_commodity_id_fkey', 'commission_structures', 'commodities', ['commodity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('commission_structures_trade_type_id_fkey', 'commission_structures', 'trade_types', ['trade_type_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_commission_trade_type_id', 'commission_structures', ['trade_type_id'], unique=False)
    op.create_index('ix_commission_is_active', 'commission_structures', ['is_active'], unique=False)
    op.create_index('ix_commission_commodity_id', 'commission_structures', ['commodity_id'], unique=False)
    op.alter_column('commission_structures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('commission_structures', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'bargain_types', type_='unique')
    op.create_index('ix_bargain_types_is_active', 'bargain_types', ['is_active'], unique=False)
    op.alter_column('bargain_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('bargain_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('bargain_types', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('bargain_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='locations_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='locations_pkey')
    )
    op.drop_index(op.f('ix_settings_locations_state'), table_name='settings_locations')
    op.drop_index('ix_settings_locations_region', table_name='settings_locations')
    op.drop_index('ix_settings_locations_pincode', table_name='settings_locations')
    op.drop_index(op.f('ix_settings_locations_name'), table_name='settings_locations')
    op.drop_index('ix_settings_locations_is_active', table_name='settings_locations')
    op.drop_index('ix_settings_locations_google_place_id', table_name='settings_locations')
    op.drop_index('ix_settings_locations_city', table_name='settings_locations')
    op.drop_table('settings_locations')
    # ### end Alembic commands ###
