"""add_user_sessions_table

Revision ID: 9a8b7c6d5e4f
Revises: ebf8bb791693
Create Date: 2025-11-23 14:30:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9a8b7c6d5e4f'
down_revision = 'ebf8bb791693'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False, comment='User who owns this session'),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=False, comment='SHA256 hash of user-agent (for device identification)'),
    sa.Column('device_name', sa.String(length=255), nullable=False, comment="Friendly device name (e.g., 'iPhone 13 (iOS 15.0)')"),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='mobile, desktop, tablet, bot'),
    sa.Column('os_name', sa.String(length=100), nullable=True, comment='Operating system (iOS, Android, Windows, macOS)'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='OS version'),
    sa.Column('browser_name', sa.String(length=100), nullable=True, comment='Browser name (Chrome, Safari, Firefox)'),
    sa.Column('browser_version', sa.String(length=50), nullable=True, comment='Browser version'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=False, comment='Full User-Agent header'),
    sa.Column('refresh_token_jti', sa.String(length=64), nullable=False, comment='JWT ID of current refresh token'),
    sa.Column('access_token_jti', sa.String(length=64), nullable=False, comment='JWT ID of current access token'),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Access token expiration'),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Refresh token expiration (session expiry)'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False, comment='Last API request from this session'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Session is active (not logged out)'),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False, comment='Flagged as suspicious login'),
    sa.Column('suspicious_reason', sa.String(length=500), nullable=True, comment='Why flagged as suspicious'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Device verified via email/SMS'),
    sa.Column('total_logins', sa.Integer(), nullable=False, comment='Total logins from this device'),
    sa.Column('failed_logins_last_24h', sa.Integer(), nullable=False, comment='Failed login attempts (security monitoring)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Session created (first login)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_device_fingerprint'), 'user_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_last_active_at'), 'user_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_expires_at'), 'user_sessions', ['refresh_token_expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_last_active_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_fingerprint'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
