"""Add international trade fields to availability and requirement

Revision ID: b6c40c1a6988
Revises: 535888366798
Create Date: 2025-12-03 15:11:49.077685

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6c40c1a6988'
down_revision = '535888366798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('currency_code', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217): INR, USD, EUR, etc.'))
    op.add_column('availabilities', sa.Column('country_of_origin', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 country code (IN, US, BR, etc.)'))
    op.add_column('availabilities', sa.Column('supported_incoterms', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of supported Incoterms: ["FOB", "CIF", "EXW", "DDP"]'))
    op.add_column('availabilities', sa.Column('export_port', sa.String(length=255), nullable=True, comment='Port code for international shipments (e.g., INNSA for Nhava Sheva)'))
    op.create_index(op.f('ix_availabilities_country_of_origin'), 'availabilities', ['country_of_origin'], unique=False)
    op.drop_index('ix_business_partners_partner_type', table_name='business_partners')
    op.drop_column('business_partners', 'partner_type')
    op.drop_column('business_partners', 'trade_classification')
    op.add_column('commission_structures', sa.Column('currency', sa.String(length=3), server_default='INR', nullable=True))
    op.add_column('commission_structures', sa.Column('rate_per_country', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commission_structures', sa.Column('forex_adjustment', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('commission_structures', sa.Column('apply_forex_on_cross_border', sa.Boolean(), nullable=False))
    op.add_column('commission_structures', sa.Column('international_tier_rates', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('default_currency', sa.String(length=3), server_default='USD', nullable=True))
    op.add_column('commodities', sa.Column('supported_currencies', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('international_pricing_unit', sa.String(length=50), nullable=True))
    op.add_column('commodities', sa.Column('hs_code_6digit', sa.String(length=6), nullable=True))
    op.add_column('commodities', sa.Column('country_tax_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('quality_standards', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('international_grades', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('certification_required', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('major_producing_countries', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('major_consuming_countries', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('trading_hubs', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('traded_on_exchanges', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('contract_specifications', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('price_volatility', sa.String(length=20), nullable=True))
    op.add_column('commodities', sa.Column('export_regulations', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('import_regulations', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('phytosanitary_required', sa.Boolean(), nullable=False))
    op.add_column('commodities', sa.Column('fumigation_required', sa.Boolean(), nullable=False))
    op.add_column('commodities', sa.Column('seasonal_commodity', sa.Boolean(), nullable=False))
    op.add_column('commodities', sa.Column('harvest_season', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('commodities', sa.Column('storage_conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('standard_lot_size', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('min_order_quantity', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('commodities', sa.Column('delivery_tolerance_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('commodities', sa.Column('weight_tolerance_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_commodities_hs_code_6digit'), 'commodities', ['hs_code_6digit'], unique=False)
    op.add_column('partner_onboarding_applications', sa.Column('entity_class', sa.String(length=20), nullable=True, comment='business_entity or service_provider'))
    op.add_column('partner_onboarding_applications', sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Trading capabilities from CDPS'))
    op.drop_column('partner_onboarding_applications', 'partner_type')
    op.drop_column('partner_onboarding_applications', 'trade_classification')
    op.add_column('payment_terms', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('payment_terms', sa.Column('supports_multi_currency', sa.Boolean(), nullable=False))
    op.add_column('payment_terms', sa.Column('supports_letter_of_credit', sa.Boolean(), nullable=False))
    op.add_column('payment_terms', sa.Column('lc_types_supported', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_terms', sa.Column('lc_confirmation_required', sa.Boolean(), nullable=False))
    op.add_column('payment_terms', sa.Column('bank_charges_borne_by', sa.String(length=20), nullable=True))
    op.add_column('payment_terms', sa.Column('forex_adjustment_applicable', sa.Boolean(), nullable=False))
    op.add_column('payment_terms', sa.Column('payment_methods_supported', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_terms', sa.Column('swift_required', sa.Boolean(), nullable=False))
    op.add_column('requirements', sa.Column('destination_country', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 country code for import destination (IN, US, CN, etc.)'))
    op.add_column('requirements', sa.Column('preferred_incoterm', sa.String(length=10), nullable=True, comment='Preferred Incoterm for international trade: FOB, CIF, EXW, DDP, etc.'))
    op.add_column('requirements', sa.Column('import_port', sa.String(length=255), nullable=True, comment='Port code for international imports (e.g., INNSA for Nhava Sheva)'))
    op.create_index(op.f('ix_requirements_destination_country'), 'requirements', ['destination_country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_destination_country'), table_name='requirements')
    op.drop_column('requirements', 'import_port')
    op.drop_column('requirements', 'preferred_incoterm')
    op.drop_column('requirements', 'destination_country')
    op.drop_column('payment_terms', 'swift_required')
    op.drop_column('payment_terms', 'payment_methods_supported')
    op.drop_column('payment_terms', 'forex_adjustment_applicable')
    op.drop_column('payment_terms', 'bank_charges_borne_by')
    op.drop_column('payment_terms', 'lc_confirmation_required')
    op.drop_column('payment_terms', 'lc_types_supported')
    op.drop_column('payment_terms', 'supports_letter_of_credit')
    op.drop_column('payment_terms', 'supports_multi_currency')
    op.drop_column('payment_terms', 'currency')
    op.add_column('partner_onboarding_applications', sa.Column('trade_classification', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('partner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('partner_onboarding_applications', 'capabilities')
    op.drop_column('partner_onboarding_applications', 'entity_class')
    op.drop_index(op.f('ix_commodities_hs_code_6digit'), table_name='commodities')
    op.drop_column('commodities', 'weight_tolerance_pct')
    op.drop_column('commodities', 'delivery_tolerance_pct')
    op.drop_column('commodities', 'min_order_quantity')
    op.drop_column('commodities', 'standard_lot_size')
    op.drop_column('commodities', 'storage_conditions')
    op.drop_column('commodities', 'shelf_life_days')
    op.drop_column('commodities', 'harvest_season')
    op.drop_column('commodities', 'seasonal_commodity')
    op.drop_column('commodities', 'fumigation_required')
    op.drop_column('commodities', 'phytosanitary_required')
    op.drop_column('commodities', 'import_regulations')
    op.drop_column('commodities', 'export_regulations')
    op.drop_column('commodities', 'price_volatility')
    op.drop_column('commodities', 'contract_specifications')
    op.drop_column('commodities', 'traded_on_exchanges')
    op.drop_column('commodities', 'trading_hubs')
    op.drop_column('commodities', 'major_consuming_countries')
    op.drop_column('commodities', 'major_producing_countries')
    op.drop_column('commodities', 'certification_required')
    op.drop_column('commodities', 'international_grades')
    op.drop_column('commodities', 'quality_standards')
    op.drop_column('commodities', 'country_tax_codes')
    op.drop_column('commodities', 'hs_code_6digit')
    op.drop_column('commodities', 'international_pricing_unit')
    op.drop_column('commodities', 'supported_currencies')
    op.drop_column('commodities', 'default_currency')
    op.drop_column('commission_structures', 'international_tier_rates')
    op.drop_column('commission_structures', 'apply_forex_on_cross_border')
    op.drop_column('commission_structures', 'forex_adjustment')
    op.drop_column('commission_structures', 'rate_per_country')
    op.drop_column('commission_structures', 'currency')
    op.add_column('business_partners', sa.Column('trade_classification', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='DEPRECATED: domestic, exporter (foreign selling to India), importer (foreign buying from India)'))
    op.add_column('business_partners', sa.Column('partner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='DEPRECATED: seller, buyer, trader, broker, sub_broker, transporter, controller, financer, shipping_agent, importer, exporter'))
    op.create_index('ix_business_partners_partner_type', 'business_partners', ['partner_type'], unique=False)
    op.drop_index(op.f('ix_availabilities_country_of_origin'), table_name='availabilities')
    op.drop_column('availabilities', 'export_port')
    op.drop_column('availabilities', 'supported_incoterms')
    op.drop_column('availabilities', 'country_of_origin')
    op.drop_column('availabilities', 'currency_code')
    # ### end Alembic commands ###
