"""Add HSN knowledge base for AI learning system

Revision ID: bdea096fec3e
Revises: e59a4a6de0ba
Create Date: 2025-11-24 06:17:10.136782

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdea096fec3e'
down_revision = 'e59a4a6de0ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsn_knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_name', sa.String(length=200), nullable=False),
    sa.Column('commodity_category', sa.String(length=100), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('hsn_description', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_name', 'hsn_code', name='uix_commodity_hsn')
    )
    op.create_index(op.f('ix_hsn_knowledge_base_commodity_category'), 'hsn_knowledge_base', ['commodity_category'], unique=False)
    op.create_index(op.f('ix_hsn_knowledge_base_commodity_name'), 'hsn_knowledge_base', ['commodity_name'], unique=False)
    op.create_index(op.f('ix_hsn_knowledge_base_hsn_code'), 'hsn_knowledge_base', ['hsn_code'], unique=False)
    op.drop_index('ix_user_sessions_device_fingerprint', table_name='user_sessions')
    op.drop_index('ix_user_sessions_is_active', table_name='user_sessions')
    op.drop_index('ix_user_sessions_last_active_at', table_name='user_sessions')
    op.drop_index('ix_user_sessions_refresh_token_expires_at', table_name='user_sessions')
    op.drop_index('ix_user_sessions_refresh_token_jti', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_consent_versions_consent_type', table_name='consent_versions')
    op.drop_index('ix_consent_versions_is_active', table_name='consent_versions')
    op.drop_table('consent_versions')
    op.drop_index('ix_data_retention_policies_data_category', table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index('ix_user_right_requests_user_id', table_name='user_right_requests')
    op.drop_table('user_right_requests')
    op.drop_index('ix_user_consents_consent_type', table_name='user_consents')
    op.drop_index('ix_user_consents_given', table_name='user_consents')
    op.drop_index('ix_user_consents_user_id', table_name='user_consents')
    op.drop_table('user_consents')
    op.add_column('business_partners', sa.Column('partner_code', sa.String(length=50), nullable=True, comment='Auto-generated: BP-IND-SEL-0001'))
    op.add_column('business_partners', sa.Column('legal_name', sa.String(length=500), nullable=False))
    op.add_column('business_partners', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('business_partners', sa.Column('business_entity_type', sa.String(length=100), nullable=True, comment='proprietorship, partnership, llp, private_limited, public_limited, corporation'))
    op.add_column('business_partners', sa.Column('registration_date', sa.Date(), nullable=True, comment='From tax registration'))
    op.add_column('business_partners', sa.Column('has_tax_registration', sa.Boolean(), nullable=True))
    op.add_column('business_partners', sa.Column('tax_id_type', sa.String(length=20), nullable=True, comment='GST, EIN, TRN, VAT, etc.'))
    op.add_column('business_partners', sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='GST: {gstin, legal_name, trade_name, status, state, directors, additional_places, other_state_gstins}'))
    op.add_column('business_partners', sa.Column('tax_verified', sa.Boolean(), nullable=True))
    op.add_column('business_partners', sa.Column('tax_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_partners', sa.Column('pan_name', sa.String(length=500), nullable=True))
    op.add_column('business_partners', sa.Column('pan_verified', sa.Boolean(), nullable=True))
    op.add_column('business_partners', sa.Column('has_no_gst_declaration', sa.Boolean(), nullable=True))
    op.add_column('business_partners', sa.Column('no_gst_declaration_url', sa.String(length=1000), nullable=True))
    op.add_column('business_partners', sa.Column('declaration_reason', sa.String(length=200), nullable=True, comment='commission_agent, turnover_below_threshold, exempted_category'))
    op.add_column('business_partners', sa.Column('bank_account_name', sa.String(length=200), nullable=False))
    op.add_column('business_partners', sa.Column('bank_name', sa.String(length=200), nullable=False))
    op.add_column('business_partners', sa.Column('bank_account_number', sa.String(length=100), nullable=False))
    op.add_column('business_partners', sa.Column('bank_routing_code', sa.String(length=50), nullable=False, comment='IFSC (India), Routing (USA), SWIFT/IBAN (International)'))
    op.add_column('business_partners', sa.Column('bank_verified', sa.Boolean(), nullable=True))
    op.add_column('business_partners', sa.Column('primary_contact_name', sa.String(length=200), nullable=False))
    op.add_column('business_partners', sa.Column('last_kyc_renewal_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('business_partners', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this partner belongs to (for data isolation)',
               existing_nullable=False)
    op.alter_column('business_partners', 'partner_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_comment='seller, buyer, trader, broker, sub_broker, transporter, controller, financer, shipping_agent, importer, exporter',
               existing_nullable=False)
    op.alter_column('business_partners', 'service_provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment='For service providers: broker, sub_broker, transporter, controller, financer, shipping_agent',
               existing_nullable=True)
    op.alter_column('business_partners', 'trade_classification',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='domestic, exporter (foreign selling to India), importer (foreign buying from India)',
               existing_comment='domestic, exporter, importer',
               existing_nullable=True)
    op.alter_column('business_partners', 'tax_id_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               nullable=True,
               comment=None,
               existing_comment='GSTIN')
    op.alter_column('business_partners', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('business_partners', 'location_confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               comment='Google Maps geocoding confidence 0-100',
               existing_nullable=True)
    op.alter_column('business_partners', 'primary_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('business_partners', 'commodities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='["cotton", "cotton_yarn", "textiles"]',
               existing_nullable=True)
    op.alter_column('business_partners', 'payment_terms_days',
               existing_type=sa.INTEGER(),
               comment='0=advance, 15, 30, 45',
               existing_nullable=True)
    op.alter_column('business_partners', 'service_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Transporter: {fleet_size, routes, vehicle_types, has_own_vehicles, transport_license}, Broker: {license_number, exchange, commission_structure}',
               existing_nullable=True)
    op.alter_column('business_partners', 'risk_assessment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Detailed scoring breakdown and flags',
               existing_nullable=True)
    op.alter_column('business_partners', 'kyc_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Initial KYC verification date (approval date)',
               existing_nullable=True)
    op.alter_column('business_partners', 'kyc_expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               comment='1 year from approval - triggers renewal',
               existing_nullable=True)
    op.alter_column('business_partners', 'kyc_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, verified, expired, renewal_required',
               existing_nullable=True)
    op.alter_column('business_partners', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='pending, approved, rejected, suspended, inactive')
    op.alter_column('business_partners', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_business_partners_email', table_name='business_partners')
    op.drop_index('ix_business_partners_is_deleted', table_name='business_partners')
    op.drop_index('ix_business_partners_kyc_expiry', table_name='business_partners')
    op.drop_index('ix_business_partners_kyc_status', table_name='business_partners')
    op.drop_index('ix_business_partners_kyc_status_expiry', table_name='business_partners', postgresql_where='(is_deleted = false)')
    op.drop_index('ix_business_partners_name_search', table_name='business_partners', postgresql_using='gin')
    op.drop_index('ix_business_partners_pan', table_name='business_partners')
    op.drop_index('ix_business_partners_phone', table_name='business_partners')
    op.drop_index('ix_business_partners_state_status', table_name='business_partners', postgresql_where='(is_deleted = false)')
    op.drop_index('ix_business_partners_status', table_name='business_partners')
    op.drop_index('ix_business_partners_tax_id', table_name='business_partners')
    op.drop_constraint('uq_partners_org_tax_id', 'business_partners', type_='unique')
    op.create_index(op.f('ix_business_partners_country'), 'business_partners', ['country'], unique=False)
    op.create_index(op.f('ix_business_partners_legal_name'), 'business_partners', ['legal_name'], unique=False)
    op.create_index(op.f('ix_business_partners_pan_number'), 'business_partners', ['pan_number'], unique=False)
    op.create_index(op.f('ix_business_partners_tax_id_number'), 'business_partners', ['tax_id_number'], unique=True)
    op.create_unique_constraint(None, 'business_partners', ['partner_code'])
    op.drop_constraint('business_partners_organization_id_fkey', 'business_partners', type_='foreignkey')
    op.create_foreign_key(None, 'business_partners', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('business_partners', 'entity_type')
    op.drop_column('business_partners', 'rejected_at')
    op.drop_column('business_partners', 'primary_contact_person')
    op.drop_column('business_partners', 'approval_notes')
    op.drop_column('business_partners', 'business_registration_number')
    op.drop_column('business_partners', 'rejected_by')
    op.drop_column('business_partners', 'legal_business_name')
    op.drop_column('business_partners', 'business_registration_date')
    op.drop_column('business_partners', 'kyc_last_renewed_at')
    op.add_column('partner_amendments', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('partner_amendments', sa.Column('field_changed', sa.String(length=100), nullable=True))
    op.add_column('partner_amendments', sa.Column('chat_transcript', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('partner_amendments', 'amendment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='add_location, change_bank, update_gst, increase_credit_limit, add_employee',
               existing_nullable=False)
    op.alter_column('partner_amendments', 'old_value',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('partner_amendments', 'new_value',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('partner_amendments', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('partner_amendments', 'supporting_documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Document IDs',
               existing_nullable=True)
    op.alter_column('partner_amendments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, approved, rejected',
               existing_nullable=True)
    op.drop_index('ix_partner_amendments_partner_id', table_name='partner_amendments')
    op.drop_index('ix_partner_amendments_status', table_name='partner_amendments')
    op.create_index(op.f('ix_partner_amendments_organization_id'), 'partner_amendments', ['organization_id'], unique=False)
    op.drop_constraint('partner_amendments_partner_id_fkey', 'partner_amendments', type_='foreignkey')
    op.create_foreign_key(None, 'partner_amendments', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'partner_amendments', 'business_partners', ['partner_id'], ['id'])
    op.drop_column('partner_amendments', 'rejection_reason')
    op.drop_column('partner_amendments', 'rejected_by')
    op.drop_column('partner_amendments', 'field_name')
    op.drop_column('partner_amendments', 'rejected_at')
    op.add_column('partner_documents', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('partner_documents', sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('partner_documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('partner_documents', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('partner_documents', sa.Column('is_expired', sa.Boolean(), nullable=True))
    op.add_column('partner_documents', sa.Column('verified', sa.Boolean(), nullable=True))
    op.alter_column('partner_documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               comment='gst_certificate, pan_card, bank_proof, transport_license, vehicle_rc, etc.',
               existing_nullable=False)
    op.drop_index('ix_partner_documents_partner_id', table_name='partner_documents')
    op.drop_index('ix_partner_documents_type', table_name='partner_documents')
    op.create_index(op.f('ix_partner_documents_organization_id'), 'partner_documents', ['organization_id'], unique=False)
    op.drop_column('partner_documents', 'uploaded_by')
    op.drop_column('partner_documents', 'ocr_confidence')
    op.drop_column('partner_documents', 'deleted_at')
    op.drop_column('partner_documents', 'is_verified')
    op.drop_column('partner_documents', 'is_deleted')
    op.drop_column('partner_documents', 'deleted_by')
    op.alter_column('partner_employees', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='admin (partner owner), employee',
               existing_nullable=True)
    op.alter_column('partner_employees', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='{"create_orders": true, "view_reports": true, "approve_contracts": false}',
               existing_nullable=True)
    op.drop_index('ix_partner_employees_partner_id', table_name='partner_employees')
    op.drop_index('ix_partner_employees_user_id', table_name='partner_employees')
    op.create_index(op.f('ix_partner_employees_organization_id'), 'partner_employees', ['organization_id'], unique=False)
    op.drop_column('partner_employees', 'deleted_at')
    op.drop_column('partner_employees', 'is_active')
    op.drop_column('partner_employees', 'is_deleted')
    op.drop_column('partner_employees', 'deleted_by')
    op.add_column('partner_kyc_renewals', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('partner_kyc_renewals', sa.Column('renewal_type', sa.String(length=20), nullable=True, comment='annual, adhoc'))
    op.add_column('partner_kyc_renewals', sa.Column('renewal_due_date', sa.Date(), nullable=False))
    op.add_column('partner_kyc_renewals', sa.Column('renewal_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('renewal_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('documents_verified', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='List of document IDs verified'))
    op.add_column('partner_kyc_renewals', sa.Column('tax_re_verified', sa.Boolean(), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('bank_re_verified', sa.Boolean(), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('risk_re_assessed', sa.Boolean(), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('new_risk_score', sa.Integer(), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    op.alter_column('partner_kyc_renewals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, in_progress, completed, expired',
               existing_nullable=True)
    op.drop_index('ix_partner_kyc_renewals_due_date', table_name='partner_kyc_renewals')
    op.drop_index('ix_partner_kyc_renewals_partner_id', table_name='partner_kyc_renewals')
    op.drop_index('ix_partner_kyc_renewals_status', table_name='partner_kyc_renewals')
    op.create_index(op.f('ix_partner_kyc_renewals_organization_id'), 'partner_kyc_renewals', ['organization_id'], unique=False)
    op.drop_constraint('partner_kyc_renewals_partner_id_fkey', 'partner_kyc_renewals', type_='foreignkey')
    op.create_foreign_key(None, 'partner_kyc_renewals', 'business_partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_kyc_renewals', 'organizations', ['organization_id'], ['id'])
    op.drop_column('partner_kyc_renewals', 'initiated_at')
    op.drop_column('partner_kyc_renewals', 'verification_passed')
    op.drop_column('partner_kyc_renewals', 'verification_notes')
    op.drop_column('partner_kyc_renewals', 'completed_at')
    op.drop_column('partner_kyc_renewals', 'due_date')
    op.drop_column('partner_kyc_renewals', 'new_documents')
    op.drop_column('partner_kyc_renewals', 'initiated_by')
    op.add_column('partner_locations', sa.Column('geocoded', sa.Boolean(), nullable=True))
    op.add_column('partner_locations', sa.Column('geocode_confidence', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('partner_locations', sa.Column('contact_person', sa.String(length=200), nullable=True))
    op.add_column('partner_locations', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('partner_locations', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('partner_locations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('partner_locations', 'location_type',
               existing_type=sa.VARCHAR(length=50),
               comment='principal, additional_same_state, branch_different_state, warehouse, factory, ship_to, bill_to',
               existing_nullable=False)
    op.alter_column('partner_locations', 'is_from_gst',
               existing_type=sa.BOOLEAN(),
               comment='Auto-fetched from GST API',
               existing_nullable=True)
    op.alter_column('partner_locations', 'gstin_for_location',
               existing_type=sa.VARCHAR(length=15),
               comment='Different GSTIN if different state',
               existing_nullable=True)
    op.alter_column('partner_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_partner_locations_partner_id', table_name='partner_locations')
    op.drop_column('partner_locations', 'deleted_by')
    op.drop_column('partner_locations', 'is_primary')
    op.drop_column('partner_locations', 'created_by')
    op.drop_column('partner_locations', 'deleted_at')
    op.drop_column('partner_locations', 'location_geocoded')
    op.drop_column('partner_locations', 'location_confidence')
    op.add_column('partner_onboarding_applications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('service_provider_type', sa.String(length=50), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('trade_classification', sa.String(length=20), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('legal_name', sa.String(length=500), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('business_entity_type', sa.String(length=100), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('has_tax_registration', sa.Boolean(), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('tax_id_type', sa.String(length=20), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('tax_verified', sa.Boolean(), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('pan_name', sa.String(length=500), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('has_no_gst_declaration', sa.Boolean(), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('no_gst_declaration_url', sa.String(length=1000), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('declaration_reason', sa.String(length=200), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('bank_account_name', sa.String(length=200), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('bank_name', sa.String(length=200), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('bank_account_number', sa.String(length=100), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('bank_routing_code', sa.String(length=50), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('primary_contact_name', sa.String(length=200), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('primary_currency', sa.String(length=3), nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('commodities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('service_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('onboarding_stage', sa.String(length=50), nullable=True, comment='documents, verification, approval'))
    op.add_column('partner_onboarding_applications', sa.Column('chat_transcript', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('verification_results', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('risk_assessment', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('converted_to_partner_id', sa.UUID(), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('partner_onboarding_applications', 'partner_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('partner_onboarding_applications', 'tax_id_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('partner_onboarding_applications', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('partner_onboarding_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('ix_onboarding_apps_organization_id', table_name='partner_onboarding_applications')
    op.drop_index('ix_onboarding_apps_status', table_name='partner_onboarding_applications')
    op.create_index(op.f('ix_partner_onboarding_applications_organization_id'), 'partner_onboarding_applications', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'partner_onboarding_applications', 'users', ['user_id'], ['id'])
    op.drop_column('partner_onboarding_applications', 'entity_type')
    op.drop_column('partner_onboarding_applications', 'location_verified')
    op.drop_column('partner_onboarding_applications', 'gst_verification_data')
    op.drop_column('partner_onboarding_applications', 'verification_notes')
    op.drop_column('partner_onboarding_applications', 'rejected_at')
    op.drop_column('partner_onboarding_applications', 'gst_verified')
    op.drop_column('partner_onboarding_applications', 'approved_by')
    op.drop_column('partner_onboarding_applications', 'primary_contact_person')
    op.drop_column('partner_onboarding_applications', 'gst_verified_at')
    op.drop_column('partner_onboarding_applications', 'created_by')
    op.drop_column('partner_onboarding_applications', 'documents_count')
    op.drop_column('partner_onboarding_applications', 'rejected_by')
    op.drop_column('partner_onboarding_applications', 'legal_business_name')
    op.drop_column('partner_onboarding_applications', 'business_registration_date')
    op.drop_column('partner_onboarding_applications', 'submitted_at')
    op.drop_column('partner_onboarding_applications', 'approved_at')
    op.drop_column('partner_onboarding_applications', 'location_geocoded')
    op.drop_column('partner_onboarding_applications', 'location_confidence')
    op.add_column('partner_vehicles', sa.Column('vehicle_number', sa.String(length=20), nullable=False))
    op.add_column('partner_vehicles', sa.Column('owner_name', sa.String(length=200), nullable=True))
    op.add_column('partner_vehicles', sa.Column('maker_model', sa.String(length=200), nullable=True))
    op.add_column('partner_vehicles', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('partner_vehicles', sa.Column('rc_document_url', sa.String(length=1000), nullable=True))
    op.add_column('partner_vehicles', sa.Column('insurance_valid_till', sa.Date(), nullable=True))
    op.add_column('partner_vehicles', sa.Column('fitness_valid_till', sa.Date(), nullable=True))
    op.add_column('partner_vehicles', sa.Column('verified_via_rto', sa.Boolean(), nullable=True))
    op.add_column('partner_vehicles', sa.Column('rto_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data from Parivahan/Vahan API'))
    op.add_column('partner_vehicles', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('partner_vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='truck, trailer, container, etc.',
               existing_nullable=False)
    op.drop_index('ix_partner_vehicles_partner_id', table_name='partner_vehicles')
    op.drop_index('ix_partner_vehicles_registration', table_name='partner_vehicles')
    op.drop_constraint('uq_vehicle_registration', 'partner_vehicles', type_='unique')
    op.create_index(op.f('ix_partner_vehicles_organization_id'), 'partner_vehicles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_partner_vehicles_vehicle_number'), 'partner_vehicles', ['vehicle_number'], unique=True)
    op.drop_column('partner_vehicles', 'rto_verified')
    op.drop_column('partner_vehicles', 'rto_verified_at')
    op.drop_column('partner_vehicles', 'insurance_valid_until')
    op.drop_column('partner_vehicles', 'is_active')
    op.drop_column('partner_vehicles', 'model')
    op.drop_column('partner_vehicles', 'fitness_valid_until')
    op.drop_column('partner_vehicles', 'updated_at')
    op.drop_column('partner_vehicles', 'created_by')
    op.drop_column('partner_vehicles', 'deleted_at')
    op.drop_column('partner_vehicles', 'registration_number')
    op.drop_column('partner_vehicles', 'updated_by')
    op.drop_column('partner_vehicles', 'year_of_manufacture')
    op.drop_column('partner_vehicles', 'manufacturer')
    op.drop_column('partner_vehicles', 'rto_verification_data')
    op.drop_column('partner_vehicles', 'is_deleted')
    op.drop_column('partner_vehicles', 'deleted_by')
    op.drop_index('ix_settings_locations_google_place_id_unique', table_name='settings_locations')
    op.create_index(op.f('ix_settings_locations_google_place_id'), 'settings_locations', ['google_place_id'], unique=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='SUPER_ADMIN, INTERNAL, or EXTERNAL',
               existing_nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               comment='For INTERNAL users only',
               existing_nullable=True)
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Mobile number for OTP authentication',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Null for OTP-only users',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Mobile/email verified via OTP',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='User role: partner_user, manager, director, etc.',
               existing_nullable=True)
    op.drop_index('ix_users_business_partner_id', table_name='users', postgresql_where='(business_partner_id IS NOT NULL)')
    op.drop_index('ix_users_organization_id', table_name='users', postgresql_where='(organization_id IS NOT NULL)')
    op.drop_index('ix_users_user_type', table_name='users')
    op.drop_constraint('uq_users_mobile_number', 'users', type_='unique')
    op.drop_index('ix_users_mobile_number', table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_foreign_key(None, 'users', 'business_partners', ['business_partner_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index('ix_users_mobile_number', 'users', ['mobile_number'], unique=False)
    op.create_unique_constraint('uq_users_mobile_number', 'users', ['mobile_number'])
    op.create_index('ix_users_user_type', 'users', ['user_type'], unique=False)
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False, postgresql_where='(organization_id IS NOT NULL)')
    op.create_index('ix_users_business_partner_id', 'users', ['business_partner_id'], unique=False, postgresql_where='(business_partner_id IS NOT NULL)')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='User role: partner_user, manager, director, etc.',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Mobile/email verified via OTP',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Null for OTP-only users',
               existing_nullable=True)
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mobile number for OTP authentication',
               existing_nullable=True)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='For INTERNAL users only',
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'INTERNAL'::character varying"),
               existing_comment='SUPER_ADMIN, INTERNAL, or EXTERNAL',
               existing_nullable=False)
    op.drop_index(op.f('ix_settings_locations_google_place_id'), table_name='settings_locations')
    op.create_index('ix_settings_locations_google_place_id_unique', 'settings_locations', ['google_place_id'], unique=True)
    op.add_column('partner_vehicles', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('rto_verification_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('year_of_manufacture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('partner_vehicles', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('partner_vehicles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('fitness_valid_until', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('insurance_valid_until', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('rto_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_vehicles', sa.Column('rto_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_partner_vehicles_vehicle_number'), table_name='partner_vehicles')
    op.drop_index(op.f('ix_partner_vehicles_organization_id'), table_name='partner_vehicles')
    op.create_unique_constraint('uq_vehicle_registration', 'partner_vehicles', ['registration_number'])
    op.create_index('ix_partner_vehicles_registration', 'partner_vehicles', ['registration_number'], unique=False)
    op.create_index('ix_partner_vehicles_partner_id', 'partner_vehicles', ['partner_id'], unique=False)
    op.alter_column('partner_vehicles', 'vehicle_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='truck, trailer, container, etc.',
               existing_nullable=False)
    op.drop_column('partner_vehicles', 'status')
    op.drop_column('partner_vehicles', 'rto_data')
    op.drop_column('partner_vehicles', 'verified_via_rto')
    op.drop_column('partner_vehicles', 'fitness_valid_till')
    op.drop_column('partner_vehicles', 'insurance_valid_till')
    op.drop_column('partner_vehicles', 'rc_document_url')
    op.drop_column('partner_vehicles', 'registration_date')
    op.drop_column('partner_vehicles', 'maker_model')
    op.drop_column('partner_vehicles', 'owner_name')
    op.drop_column('partner_vehicles', 'vehicle_number')
    op.add_column('partner_onboarding_applications', sa.Column('location_confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('location_geocoded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('business_registration_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('legal_business_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('rejected_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('documents_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('gst_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('primary_contact_person', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('partner_onboarding_applications', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('gst_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('gst_verification_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('location_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_onboarding_applications', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'partner_onboarding_applications', type_='foreignkey')
    op.drop_index(op.f('ix_partner_onboarding_applications_organization_id'), table_name='partner_onboarding_applications')
    op.create_index('ix_onboarding_apps_status', 'partner_onboarding_applications', ['status'], unique=False)
    op.create_index('ix_onboarding_apps_organization_id', 'partner_onboarding_applications', ['organization_id'], unique=False)
    op.alter_column('partner_onboarding_applications', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('partner_onboarding_applications', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('partner_onboarding_applications', 'tax_id_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('partner_onboarding_applications', 'partner_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('partner_onboarding_applications', 'updated_at')
    op.drop_column('partner_onboarding_applications', 'converted_at')
    op.drop_column('partner_onboarding_applications', 'converted_to_partner_id')
    op.drop_column('partner_onboarding_applications', 'risk_assessment')
    op.drop_column('partner_onboarding_applications', 'verification_results')
    op.drop_column('partner_onboarding_applications', 'chat_transcript')
    op.drop_column('partner_onboarding_applications', 'onboarding_stage')
    op.drop_column('partner_onboarding_applications', 'service_details')
    op.drop_column('partner_onboarding_applications', 'commodities')
    op.drop_column('partner_onboarding_applications', 'primary_currency')
    op.drop_column('partner_onboarding_applications', 'primary_contact_name')
    op.drop_column('partner_onboarding_applications', 'bank_routing_code')
    op.drop_column('partner_onboarding_applications', 'bank_account_number')
    op.drop_column('partner_onboarding_applications', 'bank_name')
    op.drop_column('partner_onboarding_applications', 'bank_account_name')
    op.drop_column('partner_onboarding_applications', 'declaration_reason')
    op.drop_column('partner_onboarding_applications', 'no_gst_declaration_url')
    op.drop_column('partner_onboarding_applications', 'has_no_gst_declaration')
    op.drop_column('partner_onboarding_applications', 'pan_name')
    op.drop_column('partner_onboarding_applications', 'tax_verified')
    op.drop_column('partner_onboarding_applications', 'tax_details')
    op.drop_column('partner_onboarding_applications', 'tax_id_type')
    op.drop_column('partner_onboarding_applications', 'has_tax_registration')
    op.drop_column('partner_onboarding_applications', 'registration_date')
    op.drop_column('partner_onboarding_applications', 'business_entity_type')
    op.drop_column('partner_onboarding_applications', 'country')
    op.drop_column('partner_onboarding_applications', 'legal_name')
    op.drop_column('partner_onboarding_applications', 'trade_classification')
    op.drop_column('partner_onboarding_applications', 'service_provider_type')
    op.drop_column('partner_onboarding_applications', 'user_id')
    op.add_column('partner_locations', sa.Column('location_confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('partner_locations', sa.Column('location_geocoded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_locations', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_locations', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('partner_locations', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_locations', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_partner_locations_partner_id', 'partner_locations', ['partner_id'], unique=False)
    op.alter_column('partner_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_locations', 'gstin_for_location',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Different GSTIN if different state',
               existing_nullable=True)
    op.alter_column('partner_locations', 'is_from_gst',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Auto-fetched from GST API',
               existing_nullable=True)
    op.alter_column('partner_locations', 'location_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='principal, additional_same_state, branch_different_state, warehouse, factory, ship_to, bill_to',
               existing_nullable=False)
    op.drop_column('partner_locations', 'updated_at')
    op.drop_column('partner_locations', 'status')
    op.drop_column('partner_locations', 'contact_phone')
    op.drop_column('partner_locations', 'contact_person')
    op.drop_column('partner_locations', 'geocode_confidence')
    op.drop_column('partner_locations', 'geocoded')
    op.add_column('partner_kyc_renewals', sa.Column('initiated_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('partner_kyc_renewals', sa.Column('new_documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('partner_kyc_renewals', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('verification_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_kyc_renewals', sa.Column('initiated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partner_kyc_renewals', type_='foreignkey')
    op.drop_constraint(None, 'partner_kyc_renewals', type_='foreignkey')
    op.create_foreign_key('partner_kyc_renewals_partner_id_fkey', 'partner_kyc_renewals', 'business_partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_partner_kyc_renewals_organization_id'), table_name='partner_kyc_renewals')
    op.create_index('ix_partner_kyc_renewals_status', 'partner_kyc_renewals', ['status'], unique=False)
    op.create_index('ix_partner_kyc_renewals_partner_id', 'partner_kyc_renewals', ['partner_id'], unique=False)
    op.create_index('ix_partner_kyc_renewals_due_date', 'partner_kyc_renewals', ['due_date'], unique=False)
    op.alter_column('partner_kyc_renewals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, in_progress, completed, expired',
               existing_nullable=True)
    op.drop_column('partner_kyc_renewals', 'created_at')
    op.drop_column('partner_kyc_renewals', 'notes')
    op.drop_column('partner_kyc_renewals', 'new_risk_score')
    op.drop_column('partner_kyc_renewals', 'risk_re_assessed')
    op.drop_column('partner_kyc_renewals', 'bank_re_verified')
    op.drop_column('partner_kyc_renewals', 'tax_re_verified')
    op.drop_column('partner_kyc_renewals', 'documents_verified')
    op.drop_column('partner_kyc_renewals', 'renewal_completed_at')
    op.drop_column('partner_kyc_renewals', 'renewal_requested_at')
    op.drop_column('partner_kyc_renewals', 'renewal_due_date')
    op.drop_column('partner_kyc_renewals', 'renewal_type')
    op.drop_column('partner_kyc_renewals', 'organization_id')
    op.add_column('partner_employees', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_employees', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_employees', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_employees', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_partner_employees_organization_id'), table_name='partner_employees')
    op.create_index('ix_partner_employees_user_id', 'partner_employees', ['user_id'], unique=False)
    op.create_index('ix_partner_employees_partner_id', 'partner_employees', ['partner_id'], unique=False)
    op.alter_column('partner_employees', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"create_orders": true, "view_reports": true, "approve_contracts": false}',
               existing_nullable=True)
    op.alter_column('partner_employees', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='admin (partner owner), employee',
               existing_nullable=True)
    op.add_column('partner_documents', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_documents', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_documents', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('partner_documents', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_documents', sa.Column('ocr_confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('partner_documents', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_partner_documents_organization_id'), table_name='partner_documents')
    op.create_index('ix_partner_documents_type', 'partner_documents', ['document_type'], unique=False)
    op.create_index('ix_partner_documents_partner_id', 'partner_documents', ['partner_id'], unique=False)
    op.alter_column('partner_documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='gst_certificate, pan_card, bank_proof, transport_license, vehicle_rc, etc.',
               existing_nullable=False)
    op.drop_column('partner_documents', 'verified')
    op.drop_column('partner_documents', 'is_expired')
    op.drop_column('partner_documents', 'expiry_date')
    op.drop_column('partner_documents', 'issue_date')
    op.drop_column('partner_documents', 'extraction_confidence')
    op.drop_column('partner_documents', 'country')
    op.add_column('partner_amendments', sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('partner_amendments', sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('partner_amendments', sa.Column('rejected_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('partner_amendments', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partner_amendments', type_='foreignkey')
    op.drop_constraint(None, 'partner_amendments', type_='foreignkey')
    op.create_foreign_key('partner_amendments_partner_id_fkey', 'partner_amendments', 'business_partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_partner_amendments_organization_id'), table_name='partner_amendments')
    op.create_index('ix_partner_amendments_status', 'partner_amendments', ['status'], unique=False)
    op.create_index('ix_partner_amendments_partner_id', 'partner_amendments', ['partner_id'], unique=False)
    op.alter_column('partner_amendments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, approved, rejected',
               existing_nullable=True)
    op.alter_column('partner_amendments', 'supporting_documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Document IDs',
               existing_nullable=True)
    op.alter_column('partner_amendments', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('partner_amendments', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('partner_amendments', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('partner_amendments', 'amendment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='add_location, change_bank, update_gst, increase_credit_limit, add_employee',
               existing_nullable=False)
    op.drop_column('partner_amendments', 'chat_transcript')
    op.drop_column('partner_amendments', 'field_changed')
    op.drop_column('partner_amendments', 'organization_id')
    op.add_column('business_partners', sa.Column('kyc_last_renewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('business_registration_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('legal_business_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('business_partners', sa.Column('rejected_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('business_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('approval_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('primary_contact_person', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('business_partners', sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('business_partners', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'business_partners', type_='foreignkey')
    op.create_foreign_key('business_partners_organization_id_fkey', 'business_partners', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'business_partners', type_='unique')
    op.drop_index(op.f('ix_business_partners_tax_id_number'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_pan_number'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_legal_name'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_country'), table_name='business_partners')
    op.create_unique_constraint('uq_partners_org_tax_id', 'business_partners', ['organization_id', 'tax_id_number'])
    op.create_index('ix_business_partners_tax_id', 'business_partners', ['tax_id_number'], unique=False)
    op.create_index('ix_business_partners_status', 'business_partners', ['status'], unique=False)
    op.create_index('ix_business_partners_state_status', 'business_partners', ['primary_state', 'status'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('ix_business_partners_phone', 'business_partners', ['primary_contact_phone'], unique=False)
    op.create_index('ix_business_partners_pan', 'business_partners', ['pan_number'], unique=False)
    op.create_index('ix_business_partners_name_search', 'business_partners', [sa.text("to_tsvector('english'::regconfig, (legal_business_name::text || ' '::text) || COALESCE(trade_name, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_business_partners_kyc_status_expiry', 'business_partners', ['kyc_status', 'kyc_expiry_date'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('ix_business_partners_kyc_status', 'business_partners', ['kyc_status'], unique=False)
    op.create_index('ix_business_partners_kyc_expiry', 'business_partners', ['kyc_expiry_date'], unique=False)
    op.create_index('ix_business_partners_is_deleted', 'business_partners', ['is_deleted'], unique=False)
    op.create_index('ix_business_partners_email', 'business_partners', ['primary_contact_email'], unique=False)
    op.alter_column('business_partners', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('business_partners', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='pending, approved, rejected, suspended, inactive')
    op.alter_column('business_partners', 'kyc_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, verified, expired, renewal_required',
               existing_nullable=True)
    op.alter_column('business_partners', 'kyc_expiry_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='1 year from approval - triggers renewal',
               existing_nullable=True)
    op.alter_column('business_partners', 'kyc_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Initial KYC verification date (approval date)',
               existing_nullable=True)
    op.alter_column('business_partners', 'risk_assessment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Detailed scoring breakdown and flags',
               existing_nullable=True)
    op.alter_column('business_partners', 'service_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Transporter: {fleet_size, routes, vehicle_types, has_own_vehicles, transport_license}, Broker: {license_number, exchange, commission_structure}',
               existing_nullable=True)
    op.alter_column('business_partners', 'payment_terms_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=advance, 15, 30, 45',
               existing_nullable=True)
    op.alter_column('business_partners', 'commodities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='["cotton", "cotton_yarn", "textiles"]',
               existing_nullable=True)
    op.alter_column('business_partners', 'primary_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('business_partners', 'location_confidence',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='Google Maps geocoding confidence 0-100',
               existing_nullable=True)
    op.alter_column('business_partners', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('business_partners', 'tax_id_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               nullable=False,
               comment='GSTIN')
    op.alter_column('business_partners', 'trade_classification',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment='domestic, exporter, importer',
               existing_comment='domestic, exporter (foreign selling to India), importer (foreign buying from India)',
               existing_nullable=True)
    op.alter_column('business_partners', 'service_provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='For service providers: broker, sub_broker, transporter, controller, financer, shipping_agent',
               existing_nullable=True)
    op.alter_column('business_partners', 'partner_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_comment='seller, buyer, trader, broker, sub_broker, transporter, controller, financer, shipping_agent, importer, exporter',
               existing_nullable=False)
    op.alter_column('business_partners', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization this partner belongs to (for data isolation)',
               existing_nullable=False)
    op.drop_column('business_partners', 'last_kyc_renewal_at')
    op.drop_column('business_partners', 'primary_contact_name')
    op.drop_column('business_partners', 'bank_verified')
    op.drop_column('business_partners', 'bank_routing_code')
    op.drop_column('business_partners', 'bank_account_number')
    op.drop_column('business_partners', 'bank_name')
    op.drop_column('business_partners', 'bank_account_name')
    op.drop_column('business_partners', 'declaration_reason')
    op.drop_column('business_partners', 'no_gst_declaration_url')
    op.drop_column('business_partners', 'has_no_gst_declaration')
    op.drop_column('business_partners', 'pan_verified')
    op.drop_column('business_partners', 'pan_name')
    op.drop_column('business_partners', 'tax_verified_at')
    op.drop_column('business_partners', 'tax_verified')
    op.drop_column('business_partners', 'tax_details')
    op.drop_column('business_partners', 'tax_id_type')
    op.drop_column('business_partners', 'has_tax_registration')
    op.drop_column('business_partners', 'registration_date')
    op.drop_column('business_partners', 'business_entity_type')
    op.drop_column('business_partners', 'country')
    op.drop_column('business_partners', 'legal_name')
    op.drop_column('business_partners', 'partner_code')
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consent_type', postgresql.ENUM('ESSENTIAL', 'FUNCTIONAL', 'ANALYTICS', 'MARKETING', 'DATA_SHARING', 'PROFILING', name='consenttype'), autoincrement=False, nullable=False),
    sa.Column('consent_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('given', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('given_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('withdrawn_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['consent_version_id'], ['consent_versions.id'], name='user_consents_consent_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_consents_pkey')
    )
    op.create_index('ix_user_consents_user_id', 'user_consents', ['user_id'], unique=False)
    op.create_index('ix_user_consents_given', 'user_consents', ['given'], unique=False)
    op.create_index('ix_user_consents_consent_type', 'user_consents', ['consent_type'], unique=False)
    op.create_table('user_right_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('ACCESS', 'RECTIFICATION', 'ERASURE', 'RESTRICTION', 'PORTABILITY', 'OBJECTION', name='userrighttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='requeststatus'), server_default=sa.text("'PENDING'::requeststatus"), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejected_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_right_requests_pkey')
    )
    op.create_index('ix_user_right_requests_user_id', 'user_right_requests', ['user_id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_category', postgresql.ENUM('USER_ACCOUNT', 'TRANSACTION', 'AUDIT_LOG', 'SESSION', 'CONSENT', 'COMMUNICATION', 'ANALYTICS', 'BACKUP', name='datacategory'), autoincrement=False, nullable=False),
    sa.Column('retention_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('legal_basis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_delete', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_retention_policies_pkey'),
    sa.UniqueConstraint('data_category', name='uq_data_category')
    )
    op.create_index('ix_data_retention_policies_data_category', 'data_retention_policies', ['data_category'], unique=False)
    op.create_table('consent_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consent_type', postgresql.ENUM('ESSENTIAL', 'FUNCTIONAL', 'ANALYTICS', 'MARKETING', 'DATA_SHARING', 'PROFILING', name='consenttype'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='consent_versions_pkey'),
    sa.UniqueConstraint('consent_type', 'version', name='uq_consent_type_version')
    )
    op.create_index('ix_consent_versions_is_active', 'consent_versions', ['is_active'], unique=False)
    op.create_index('ix_consent_versions_consent_type', 'consent_versions', ['consent_type'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='User who owns this session'),
    sa.Column('device_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='SHA256 hash of user-agent (for device identification)'),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="Friendly device name (e.g., 'iPhone 13 (iOS 15.0)')"),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='mobile, desktop, tablet, bot'),
    sa.Column('os_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Operating system (iOS, Android, Windows, macOS)'),
    sa.Column('os_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='OS version'),
    sa.Column('browser_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Browser name (Chrome, Safari, Firefox)'),
    sa.Column('browser_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Browser version'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False, comment='IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False, comment='Full User-Agent header'),
    sa.Column('refresh_token_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='JWT ID of current refresh token'),
    sa.Column('access_token_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='JWT ID of current access token'),
    sa.Column('access_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Access token expiration'),
    sa.Column('refresh_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Refresh token expiration (session expiry)'),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Last API request from this session'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Session is active (not logged out)'),
    sa.Column('is_suspicious', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Flagged as suspicious login'),
    sa.Column('suspicious_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Why flagged as suspicious'),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Device verified via email/SMS'),
    sa.Column('total_logins', sa.INTEGER(), autoincrement=False, nullable=False, comment='Total logins from this device'),
    sa.Column('failed_logins_last_24h', sa.INTEGER(), autoincrement=False, nullable=False, comment='Failed login attempts (security monitoring)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Session created (first login)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Last updated'),
    sa.PrimaryKeyConstraint('id', name='user_sessions_pkey')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_refresh_token_jti', 'user_sessions', ['refresh_token_jti'], unique=True)
    op.create_index('ix_user_sessions_refresh_token_expires_at', 'user_sessions', ['refresh_token_expires_at'], unique=False)
    op.create_index('ix_user_sessions_last_active_at', 'user_sessions', ['last_active_at'], unique=False)
    op.create_index('ix_user_sessions_is_active', 'user_sessions', ['is_active'], unique=False)
    op.create_index('ix_user_sessions_device_fingerprint', 'user_sessions', ['device_fingerprint'], unique=False)
    op.drop_index(op.f('ix_hsn_knowledge_base_hsn_code'), table_name='hsn_knowledge_base')
    op.drop_index(op.f('ix_hsn_knowledge_base_commodity_name'), table_name='hsn_knowledge_base')
    op.drop_index(op.f('ix_hsn_knowledge_base_commodity_category'), table_name='hsn_knowledge_base')
    op.drop_table('hsn_knowledge_base')
    # ### end Alembic commands ###
