"""
Availability Embedding Model - Vector embeddings for semantic search

Stores 384-dimensional vector embeddings generated by Sentence-BERT (all-MiniLM-L6-v2)
for semantic similarity search in availability matching.

Features:
- pgvector integration for cosine similarity search
- Text hash for deduplication
- Model versioning for future upgrades
- Automatic cascade delete with parent availability
- IVFFlat index for fast similarity search
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import Column, DateTime, ForeignKey, String, text
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector

from backend.db.session import Base

if TYPE_CHECKING:
    from backend.modules.trade_desk.models.availability import Availability


class AvailabilityEmbedding(Base):
    """
    Vector embeddings for availabilities - enables semantic search.
    
    Generated from:
    - Commodity name + quality parameters
    - Location and delivery terms
    - Price and availability details
    
    Used for:
    - Semantic similarity search (cosine distance)
    - Cross-commodity matching
    - AI-powered recommendation
    """
    
    __tablename__ = "availability_embeddings"
    
    # Primary Key
    id = Column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False
    )
    
    # Foreign Key (one-to-one with Availability)
    availability_id = Column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("availabilities.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True
    )
    
    # Vector embedding (384 dimensions - all-MiniLM-L6-v2)
    embedding = Column(
        Vector(384),
        nullable=False,
        comment="384-dim vector from Sentence-BERT"
    )
    
    # Text hash for deduplication
    text_hash = Column(
        String(64),
        nullable=False,
        index=True,
        comment="SHA-256 hash of source text to detect changes"
    )
    
    # Model version tracking
    model_version = Column(
        String(50),
        nullable=False,
        server_default="all-MiniLM-L6-v2",
        comment="Embedding model version"
    )
    
    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        comment="When embedding was created"
    )
    
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        onupdate=datetime.utcnow,
        comment="When embedding was last updated"
    )
    
    # Relationships
    availability = relationship(
        "Availability",
        back_populates="embedding",
        lazy="joined"
    )
    
    def __repr__(self) -> str:
        return f"<AvailabilityEmbedding(id={self.id}, availability_id={self.availability_id})>"
