"""
Negotiation Message Model - Real-time chat during negotiation

Supports:
- Human-to-human chat
- AI bot messages
- System notifications
- Message read tracking
"""

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import (
    Column, String, DateTime, ForeignKey, Boolean, Text, Index, CheckConstraint
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from backend.db.base import Base


class NegotiationMessage(Base):
    """
    Chat messages exchanged during negotiation.
    
    Message types:
        - TEXT: Regular chat message
        - OFFER: "I'm offering ₹7,150/qtl"
        - ACCEPTANCE: "I accept your offer!"
        - REJECTION: "Sorry, can't go below ₹7,200"
        - SYSTEM: "Negotiation expires in 2 hours"
        - AI_SUGGESTION: "AI suggests counter at ₹7,175"
    """
    __tablename__ = "negotiation_messages"
    
    # Primary key
    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)
    
    # Parent negotiation
    negotiation_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("negotiations.id", ondelete="CASCADE"),
        nullable=False,
        comment="Parent negotiation session"
    )
    
    # Sender
    sender = Column(
        String(10),
        nullable=False,
        comment="BUYER, SELLER, SYSTEM, AI_BOT"
    )
    
    # Message content
    message = Column(
        Text,
        nullable=False,
        comment="Message text"
    )
    
    message_type = Column(
        String(20),
        nullable=False,
        default="TEXT",
        comment="TEXT, OFFER, ACCEPTANCE, REJECTION, SYSTEM, AI_SUGGESTION"
    )
    
    # AI tracking
    is_ai_generated = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Was this generated by AI?"
    )
    
    # Read receipts
    read_by_buyer = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Has buyer read this message?"
    )
    
    read_by_seller = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Has seller read this message?"
    )
    
    read_by_buyer_at = Column(
        DateTime,
        nullable=True,
        comment="When buyer read the message"
    )
    
    read_by_seller_at = Column(
        DateTime,
        nullable=True,
        comment="When seller read the message"
    )
    
    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationships
    negotiation = relationship("Negotiation", back_populates="messages")
    
    # Constraints
    __table_args__ = (
        CheckConstraint("sender IN ('BUYER', 'SELLER', 'SYSTEM', 'AI_BOT')", name="check_message_sender"),
        CheckConstraint("message_type IN ('TEXT', 'OFFER', 'ACCEPTANCE', 'REJECTION', 'SYSTEM', 'AI_SUGGESTION')", name="check_message_type"),
        Index("idx_messages_negotiation", "negotiation_id"),
        Index("idx_messages_created", "created_at"),
        Index("idx_messages_unread_buyer", "negotiation_id", "read_by_buyer"),
        Index("idx_messages_unread_seller", "negotiation_id", "read_by_seller"),
    )
    
    def mark_read_by_buyer(self):
        """Mark message as read by buyer"""
        if not self.read_by_buyer:
            self.read_by_buyer = True
            self.read_by_buyer_at = datetime.utcnow()
    
    def mark_read_by_seller(self):
        """Mark message as read by seller"""
        if not self.read_by_seller:
            self.read_by_seller = True
            self.read_by_seller_at = datetime.utcnow()
    
    def __repr__(self) -> str:
        return f"<NegotiationMessage from={self.sender} type={self.message_type}>"
