"""
Partner AI Prompts

System prompts for partner assistant.
"""

from .prompts import (
    PARTNER_ASSISTANT_SYSTEM_PROMPT,
    ONBOARDING_START_PROMPT,
    DOCUMENT_UPLOAD_PROMPT,
    VERIFICATION_STATUS_PROMPT,
    RISK_SCORE_EXPLANATION_PROMPT,
    KYC_RENEWAL_PROMPT,
    AMENDMENT_REQUEST_PROMPT,
    EMPLOYEE_INVITE_PROMPT,
    FAQ_PROMPT,
)

__all__ = [
    "PARTNER_ASSISTANT_SYSTEM_PROMPT",
    "ONBOARDING_START_PROMPT",
    "DOCUMENT_UPLOAD_PROMPT",
    "VERIFICATION_STATUS_PROMPT",
    "RISK_SCORE_EXPLANATION_PROMPT",
    "KYC_RENEWAL_PROMPT",
    "AMENDMENT_REQUEST_PROMPT",
    "EMPLOYEE_INVITE_PROMPT",
    "FAQ_PROMPT",
]
